### ISSUE TITLE
Verify Getting Started

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/generellem#36]
The [Getting Started](https://github.com/generellem/generellem/wiki/Getting-Started) documentation needs to be as simple as possible. We also need a double-check to verify that it works the same for more than the people who created it.

Test the Getting Started to ensure it works and provide feedback if you have suggestions on how it could be made easier.

**Comment by jennifermayo** [comment]
@JoeMayo I can grab this one and do it before the end of the month.

**Comment by JoeMayo** [comment]
Assigned to you - Thanks!

**Comment by JoeMayo** [comment]
I took a quick look at this and noticed that the environment variable names were out of date because of recent work I did on configuration. Those are updated now.

**Comment by jennifermayo** [comment]
I went through Getting Started and was able to get Generellem working on my machine! I made some small updates to the organization of the page and added a few tips for the Azure set up portion:
https://github.com/generellem/generellem/wiki/Getting-Started

**Comment by JoeMayo** [comment]
The new [Getting Started](https://github.com/generellem/generellem/wiki/Getting-Started) page looks good. I see the [Context Length Bug](https://github.com/users/generellem/projects/2/views/1?pane=issue&itemId=50463583) you opened too.

I think this task is done and you're welcome to close it.

Thank you!
