### ISSUE TITLE
Automate Default Azure OpenAI Deployment

### ISSUE THREAD

**Issue by JoeMayo** [JoeMayo/generellem#37]
We want to simplify [Getting Started](https://github.com/generellem/generellem/wiki/Getting-Started) for anyone who wants to try Generellem. We can build a script that uses Azure CLI to automate these tasks. The script should be cross-platform for Linux, MacOS, and Windows. Here's an example that might help to point in the right direction:

https://github.com/microsoft/generative-ai-for-beginners/blob/main/08-building-search-applications/README.md?WT.mc_id=academic-105485-koreyst

**Comment by marchosana** [comment]
Currently working on this!
